### ISSUE TITLE
mouse selection is also pull editor line numbers

### ISSUE THREAD

**Issue by padrian2s** [curlpipe/ox#57] opened 2020-11-04 14:46 UTC
**Is your feature request related to a problem? Please describe.**

is easy to use mouse for selecting lines

**Describe the solution you'd like**

please don't include line numbers on mouse selection of text when copy/paste.

**Describe alternatives you've considered**

**Comment by curlpipe** [comment] 2020-11-04 17:56
Duplicate of #21

**Closed by curlpipe** 2020-11-04 17:57 UTC
