### ISSUE TITLE
sometimes can't edit  the last line of files

### ISSUE THREAD

**Issue by kurokirasama** [curlpipe/ox#131] opened 2024-07-22 01:12 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/e9ab7625-d261-4ede-9632-177595cb586d

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubuntu 20.04

**Comment by curlpipe** [comment] 2024-07-22 10:26
Hi, thanks for reporting this issue

Unfortunately, it looks like the video you've linked has somehow corrupted.

I have a suspicion about what could be causing this, and I think it may have been fixed in 0.4.2

It might be worth just updating and checking that this issue still remains

**Comment by kurokirasama** [comment] 2024-07-22 15:06
Hey, I just updated to 0.4.2 and the issue persists. Here's a link to the video: [ox](https://bit.ly/4feYEfv)

**Comment by curlpipe** [comment] 2024-07-22 18:42
So it seems like Ox thinks the length of your file `prompt.md` is less than it actually is, which causes it to not register "however" as part of the document, hence the weird behaviour. I'm not sure what caused this, but I can certainly investigate.

Did you write this `prompt.md` file in Ox? Or did you write it in another editor?

If you could send me the `prompt.md` file itself, that would be very helpful, just so I can try and reproduce the error.

**Comment by kurokirasama** [comment] 2024-07-22 22:35
hey, thanks for your time. 
The file wast created with sublime text.
I've re-wrote the file several times and right now the error isn't there. If it happens again, I'll post it here.

**Comment by curlpipe** [comment] 2024-07-23 09:53
Great, I close this for now, if it reappears, it can be re-opened :+1:

**Comment by kurokirasama** [comment] 2024-08-05 15:47
Hey, here is another example of this.

https://github.com/user-attachments/assets/8f904766-8c6b-45b8-85be-86f5caea1317

**Comment by curlpipe** [comment] 2024-09-16 16:04
I've been able to reproduce this error!

**Comment by curlpipe** [comment] 2024-09-16 16:08
Ok, so the issue is down to this file not having an end of line character. I'll have Ox recognise this and work around it :+1:

**Comment by curlpipe** [comment] 2024-09-16 16:42
Fixed in 0.5.3

**Closed by curlpipe** 2024-09-16 16:42 UTC
