### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by micahcantor** [curlpipe/ox#101] opened 2020-12-07 05:04 UTC
**Describe the bug**
ox crashes with an index out of bounds error, when pressing backspace in an empty file.

**To Reproduce**
1. run `ox`
2. press backspace twice
3. error prints to std out and ox quits

**Expected behavior**
Ox does not crash when pressing backspace in an empty file

**Screenshots**
 thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/document.rs:385:21                                                                              
stack backtrace:                                                              
0:     0x55c15ffc3273 - <unknown>                          
1:     0x55c15ff4611c - <unknown>                                                                                                                                                                                
2:     0x55c15ffc28d6 - <unknown>                                                                                                                                            
3:     0x55c15ffc22ca - <unknown>                                                                                                        
 4:     0x55c15ffc1b97 - <unknown>                                                                    
5:     0x55c15ffc182a - <unknown>                                
6:     0x55c15ffc17f4 - <unknown>                                                                                                                                                                                      
7:     0x55c15ffc17ad - <unknown>                                                                                                                                                  
8:     0x55c15ff438e0 - <unknown>                                                                                                              
9:     0x55c15ff43771 - <unknown>                                                                          
10:     0x55c15fed529c - <unknown>                                      
11:     0x55c15fee6784 - <unknown>  
12:     0x55c15fea7043 - <unknown>                                                                                                                                                        
13:     0x55c15fef0d55 - <unknown>                                                                                                                    
14:     0x7fb19de50152 - __libc_start_main                                                                        
15:     0x55c15fea506e - <unknown>                                    
16:                0x0 - <unknown>
Aborted (core dumped)  

![ox_crash](https://user-images.githubusercontent.com/42819290/101311566-b4006b00-381f-11eb-850d-a26b7c962991.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux, latest, kernel 5.9

**Comment by tengkuizdihar** [comment] 2020-12-19 10:30
I've tested it on the master branch and found that it's working fine, no index out of bounds found.
* OS: Manjaro, kernel 5.4.x

**Comment by micahcantor** [comment] 2020-12-19 15:52
I installed the version from the AUR, and I see the issue about it being out of date, so maybe this has been fixed recently?

**Comment by curlpipe** [comment] 2020-12-19 19:45
There are several problems with this editor at the moment and I am starting to see a pattern
1. Distribution - There are so many versions of Ox on different packaging systems and it's quite hard to keep up
2. Panics - I have failed to test thoroughly enough for these and Ox lacks unit tests, these are also mainly caused by the configuration file.
3. Missing features - Some features are quite large and would require a total rewrite of Ox itself.

I'm currently thinking up solutions to each of these problems and I'm currently building a Version 0.3.0 of the editor that I'm building from the ground up. I have created this version with several improvements over the 0.2.* codebase:
1. I'm looking into Github actions and teaching myself how to use all these different package managers to ensure that all copies are up to date.
2. I've split up the editor into a back end and front end, this allows me to write tests and also design the editor without repeating myself due to the code being cleaner and easier for me to read, therefore allowing me to quickly implement features and patch things because I can isolate them into the front or back end instead of them being fused together. I've already implemented a special test that checks for panics and written my code in a panic-resistant fashion (I've really improved my Rust knowledge over the past few months).
3. I'm writing a proper language (Oxa is way too buggy) similar to that of Vimscript and elisp where one can configure and write plugins for Ox. (I've been keen to learn proper lexing & parsing techniques and this is a perfect opportunity)

I have no ETA but I'm making hasty progress with this version and I know that it will create a better experience.

**Comment by curlpipe** [comment] 2020-12-19 19:46
I will also update the AUR package to the latest version now. (forgive me)

**Comment by sourlemon207** [comment] 2021-01-24 19:47
>     I'm writing a proper language (Oxa is way too buggy) similar to that of Vimscript and elisp where one can configure and write 
>     plugins for Ox. (I've been keen to learn proper lexing & parsing techniques and this is a perfect opportunity)

why not just use an existing programming language like lua

**Comment by curlpipe** [comment] 2024-07-16 11:13
It's been a while, but this should be fixed in the new version

This new version also uses Lua for configuration and writing scripts/plugins (at some point) instead of a strange proprietary language.

**Closed by curlpipe** 2024-07-16 11:13 UTC
