### ISSUE TITLE
Typing Lag with modules

### ISSUE THREAD

**Issue by ngenen** [curlpipe/ox#183] opened 2024-11-18 15:27 UTC
**What is the bug?**
When I write in the editor if i press "A" or any other key for a period of time and suddenly release it, it keeps writing for a little while.
It also happens with arrow keys if I'm scrolling down and stop, it keeps scrolling.

**What did you do to get the bug?**
I enabled the module git, typing_speed, pomodoro and updates_notification. The bug is certainly in one (or many) of this modules, when I disable them the bug is gone.

**What behaviour were you expecting?**
I expect not to get keys repeted once I release them.

**Comment by ngenen** [comment] 2024-11-18 19:51
The culprit is typing speed plugin! been testing each and the problem arises with that plugin.. I looked into the plugin code and couldn't find the problem at first sight, I would test if the event_mapping is firing like crazy..

**Comment by ngenen** [comment] 2024-11-18 20:02
I'll keep testing, I figured that when I add "--" in front of the load_plugin for typing_speed, git module stopped working too, or at least the status git message.

**Comment by ngenen** [comment] 2024-11-18 20:07
As I figured, the git plugin gets loaded but the status_line as soon as one variable used is not found, it breaks the rest of the "plugin" variables (for example, cursor_y keeps working anyhow)..

**Comment by ngenen** [comment] 2024-11-18 21:04
I'm sorry the spam, would be better a discord channel or even IRC haha. So, I found the problem, in the git.lua plugin, the function git_branch() is called every time a key is pressed, which it also calls refresh_status and it only makes sense calling it when a git action is done or every lets say 10 sec (to detect external git changes), but calling refresh_status on every keypress its whats killing it.

**Comment by curlpipe** [comment] 2024-11-19 00:00
> I'm sorry the spam, would be better a discord channel or even IRC haha. So, I found the problem, in the git.lua plugin, the function git_branch() is called every time a key is pressed, which it also calls refresh_status and it only makes sense calling it when a git action is done or every lets say 10 sec (to detect external git changes), but calling refresh_status on every keypress its whats killing it.

Thanks for the investigation, I agree, I reckon this is exactly where the issue is.

**Comment by curlpipe** [comment] 2024-12-01 21:47
So I implemented it so that a full refresh (equivalent to 2 calls to the git command) happens only under the following circumstances:

- The editor has just opened
- The user interacts with the editor and it has been 10 seconds since the last refresh
- The user presses `ctrl + s` to save

I checked and the old version of the git plug-in was casually making thousands of calls every minute or so... not so great.

You can update the git plug-in by using the `plugin update` command from within the editor, or manually downloading the new version from the GitHub repository directly ([here](https://github.com/curlpipe/ox/blob/master/plugins/git.lua)) and placing it in the `~/.config/ox/` folder

Let me know if you need any more assistance, or if you're still experiencing issues.

Closing for now, thanks for the bug report!

**Closed by curlpipe** 2024-12-01 21:47 UTC
